alias aps='aptitude search'
compdef _aps aps='aptitude search'

alias ap='sudo aptitude'
compdef _ap ap='sudo aptitude'
alias apa='sudo aptitude autoclean'
compdef _apa apa='sudo aptitude autoclean'
alias agp='sudo aptitude purge'
compdef _app app='sudo aptitude purge'
alias agu='sudo aptitude update'
compdef _apu apu='sudo aptitude update'
alias aguu='sudo aptitude update && sudo aptitude upgrade'
compdef _apuu apuu='sudo aptitude update && sudo aptitude upgrade'

alias allpkgs='aptitude search -F "%p" --disable-columns $1'