#!/usr/bin/env sh

yabai -m rule --add app="^(Python|python3|Labelme)$" title="^Labelme($| - )" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --apply

yabai -m config \
    layout bsp \
    split_type auto \
    auto_balance off \
    window_placement second_child \
    window_insertion_point focused \
    top_padding 10 \
    bottom_padding 10 \
    left_padding 10 \
    right_padding 10 \
    window_gap 10 \
    mouse_follows_focus off \
    focus_follows_mouse off

"$HOME/.local/bin/set-yabai-border-color"
yabai -m signal --add event=window_focused action="$HOME/.local/bin/set-yabai-border-color"
