# This file is automatically generated at 2018-06-12T00:55:17.127762+00:00 by command below,
# and please don't edit manually.
#
#   /Users/wkentaro/.dotfiles/docker/generate_dockerfiles.py
#
FROM ubuntu:xenial

RUN \
  apt-get update -qq && \
  apt-get upgrade -qq -y && \
  apt-get install -qq -y \
    apt-transport-https \
    aptitude \
    build-essential \
    ctags \
    curl \
    fontconfig \
    git \
    lsb-release \
    python-dev \
    python-setuptools \
    python-yaml \
    software-properties-common \
    sudo \
    unzip \
    vim \
    wget \
    zsh

RUN \
  easy_install 'pip<10' && \
  pip install -U setuptools && \
  pip install percol

RUN \
  useradd wkentaro && \
  echo wkentaro:wkentaro | chpasswd && \
  mkdir -p /home/wkentaro && \
  chown -R wkentaro:wkentaro /home/wkentaro && \
  adduser wkentaro sudo

RUN \
  chsh -s /bin/zsh wkentaro

USER wkentaro

RUN \
  git clone -q --recursive \
    https://github.com/wkentaro/dotfiles.git ~/.dotfiles && \
  cd ~/.dotfiles && \
  ./install.py && \
  echo 'source $HOME/.zshrc.wkentaro' > ~/.zshrc

USER root
ENV HOME /home/wkentaro

RUN \
  cd $HOME/.dotfiles/install_scripts && \
  set -e && \
  for fname in $(command ls *.sh | grep -v -e '.*opt\.sh$'); do bash $fname || exit 1; done && \
  set +e

RUN \
  export LANG=en_US.UTF-8 && \
  export LC_ALL=$LANG && \
  locale-gen --purge $LANG && \

RUN \
  chsh -s /usr/local/bin/zsh wkentaro

USER wkentaro
ENV HOME /home/wkentaro
ENV SHELL /usr/local/bin/zsh
CMD /usr/local/bin/zsh
